CREATE TABLE [dbo].[BaiDang] (
    [ID]         NCHAR (50)     NOT NULL,
    [IDUser]     NVARCHAR (50)  NULL,
    [TieuDe]     NVARCHAR (MAX) NULL,
    [LinhVuc]    NVARCHAR (50)  NULL,
    [KhuVuc]     NVARCHAR (50)  NULL,
    [MoTa]       NVARCHAR (MAX) NULL,
    [Date]       DATETIME (7)  NULL,
    [KinhNghiem] NVARCHAR (50)  NULL,
    [YeuCau]     NVARCHAR (MAX) NULL,
    [GhiChu]     NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


Insert into BaiDang Values ('1', N'Cần thuê thợ điện tử chuyên nghiệp cho dự án mới', N'Điện tử', N'Thủ Đức', N'Đảm bảo sửa chữa và bảo trì các thiết bị điện tử trong dự án mới, bao gồm máy tính, máy in, thiết bị điện tử khác theo yêu cầu', N'2024-3-4', N'1 - 2 năm', N'Có kinh nghiệm trong việc sửa chữa và bảo trì thiết bị điện tử, hiểu biết về các linh kiện điện tử, có khả năng xử lý sự cố.', N'Ưu tiên ứng viên có bằng cấp và chứng chỉ liên quan đến điện tử.')
Insert into BaiDang Values ('2', N'Tìm kiếm thợ điện lạnh có kinh nghiệm tại khu vực đô thị mới', N'Điện lạnh', N'Quận 1', N'Thực hiện việc sửa chữa, lắp đặt và bảo dưỡng hệ thống điều hòa không khí, tủ lạnh và các thiết bị điện lạnh khác.', N'2024-3-4', N'1 - 2 năm', N'Có kinh nghiệm ít nhất 2 năm trong lĩnh vực điện lạnh, hiểu biết vững về các loại máy lạnh và tủ lạnh, có khả năng làm việc độc lập và theo nhóm.' ,N'Ưu tiên ứng viên có khả năng giao tiếp tốt và thái độ chuyên nghiệp.')
Insert into BaiDang Values ('3', N'Gấp! Tuyển dụng thợ sửa máy tính tại nhà', N'Điện tử', N'Quận 2', N'Đi đến nhà khách hàng để kiểm tra, sửa chữa và cài đặt phần mềm cho máy tính cá nhân hoặc văn phòng.', N'2024-3-4', N'1 - 2 năm', N'Có kiến thức chuyên sâu về phần cứng và phần mềm máy tính, khả năng phát hiện và khắc phục sự cố nhanh chóng.', N'Đề xuất tính phí dịch vụ trước khi bắt đầu công việc và tuân thủ chính sách giá của công ty.')
Insert into BaiDang Values ('4', N'Cần thợ gia sư dạy kèm môn Toán lớp 10', N'Gia sư', N'Quận 3', N'Dạy kèm môn Toán cho học sinh lớp 10, giúp họ hiểu và áp dụng các kiến thức Toán học một cách hiệu quả.', N'2024-3-4', N'1 - 2 năm', N'Hiểu biết sâu rộng về chương trình Toán lớp 10, khả năng truyền đạt thông tin một cách dễ hiểu và phương pháp giảng dạy linh hoạt.', N'Ưu tiên ứng viên có kinh nghiệm làm gia sư và có kiến thức vững chắc về Toán.')
Insert into BaiDang Values ('5', N'Tìm thợ sửa nhà uy tín để cải thiện không gian sống', N'Sửa nhà', N'Quận 4', N'Thực hiện các công việc sửa chữa và nâng cấp nhà cửa, bao gồm sơn sửa, lắp đặt và cải thiện không gian sống.', N'2024-3-4', N'1 - 2 năm', N'Kỹ năng làm việc chuyên nghiệp, hiểu biết về các quy trình sửa chữa nhà cửa, có khả năng làm việc theo yêu cầu của khách hàng.', N'Ưu tiên ứng viên có kinh nghiệm làm việc trong ngành xây dựng và sửa nhà.')
Insert into BaiDang Values ('6', N'Cần thuê thợ điện nước lành nghề cho công trình xây dựng', N'Điện nước', N'Quận 5', N'Thực hiện các công việc liên quan đến hệ thống điện và nước trong công trình xây dựng, bao gồm lắp đặt, bảo trì và sửa chữa.', N'2024-3-4', N'1 - 2 năm', N'Yêu cầu có thái độ chuyên nghiệp và cẩn thận trong công việc, có trách nhiệm, hiểu biết về các vấn đề kỹ thuật và có khả năng xử lý tình huống một cách nhanh chóng.', N'Ưu tiên ứng viên có bằng cấp hoặc chứng chỉ liên quan đến điện nước và có kinh nghiệm làm việc trong ngành xây dựng.')
Insert into BaiDang Values ('7', N'Gấp! Tìm thợ bảo trì máy móc cho nhà máy sản xuất', N'Bảo Trì', N'Quận 7', N'Thực hiện bảo trì, sửa chữa và duy trì các thiết bị và máy móc trong nhà máy sản xuất để đảm bảo hoạt động suôn sẻ và an toàn.', N'2024-3-4', N'1 - 2 năm', N'Kỹ năng làm việc chuyên nghiệp, hiểu biết vững về các hệ thống điện và nước, có kinh nghiệm làm việc trong môi trường xây dựng.', N'Ưu tiên ứng viên có kinh nghiệm làm việc trong môi trường sản xuất và hiểu biết về các quy trình bảo trì máy móc.')
Insert into BaiDang Values ('8', N'Cần tuyển thợ sửa máy giặt tại gia', N'Gia sư', N'Điện lạnh', N'Cung cấp dịch vụ sửa chữa, bảo dưỡng và lắp đặt máy giặt tại nhà cho các hộ gia đình và khách hàng cá nhân.', N'2024-3-4', N'1 - 2 năm', N'Kỹ năng sửa chữa máy giặt, hiểu biết về cấu tạo và hoạt động của các loại máy giặt, có khả năng di chuyển linh hoạt và làm việc tại nhà khách hàng.', N'Ưu tiên ứng viên có kinh nghiệm làm việc trong lĩnh vực sửa chữa thiết bị gia đình.')
Insert into BaiDang Values ('9', N'Tìm kiếm thợ điện tử sửa chữa điện thoại di động', N'Điện tử', N'Quận 8', N'Thực hiện sửa chữa, thay thế linh kiện và nâng cấp phần mềm cho điện thoại di động của khách hàng.', N'2024-3-4', N'1 - 2 năm', N'Kỹ năng sửa chữa điện thoại di động, hiểu biết về các dòng điện thoại và hệ điều hành di động, có khả năng làm việc chính xác và cẩn thận.', N'Ưu tiên ứng viên có kinh nghiệm làm việc trong ngành sửa chữa điện thoại di động và có khả năng giải quyết các vấn đề kỹ thuật phức tạp.')
Insert into BaiDang Values ('10', N'Cần thợ điện lạnh để lắp đặt hệ thống điều hòa mới', N'Điện lạnh', N'Quận 9', N'Lắp đặt và cài đặt các hệ thống điều hòa không khí mới cho các căn hộ, nhà ở và văn phòng.', N'2024-3-4', N'1 - 2 năm', N'Kỹ năng lắp đặt điều hòa không khí, hiểu biết về các loại máy điều hòa và hệ thống làm lạnh, có khả năng làm việc theo yêu cầu của khách hàng.', N'Ưu tiên ứng viên có kinh nghiệm trong việc lắp đặt và bảo trì hệ thống điều hòa không khí.')

Insert into BaiDang Values ('1', N'Gấp! Cần thuê thợ gia sư môn Văn lớp 12', N'Gia Sư', N'Thủ Đức', N'Dạy kèm môn Văn cho học sinh lớp 12, giúp họ nắm vững kiến thức, kỹ năng và phương pháp làm bài thi.', N'2024-3-4', N'1 - 2 năm', N'Hiểu biết sâu rộng về chương trình Văn lớp 12, có khả năng giảng dạy một cách linh hoạt và sáng tạo.', N'Ưu tiên ứng viên có kinh nghiệm giảng dạy và hiểu biết vững chắc về Văn học.')
Insert into BaiDang Values ('2', N'Tuyển dụng thợ sửa nhà chuyên nghiệp cho dự án lớn', N'Sửa nhà', N'Quận 1', N'Thực hiện các công việc sửa chữa, xây dựng và cải thiện nhà cửa cho dự án xây dựng lớn.', N'2024-3-4', N'1 - 2 năm', N'Kỹ năng làm việc chuyên nghiệp, hiểu biết về các quy trình xây dựng và sửa nhà, có khả năng quản lý thời gian và nguồn lực.' ,N'Ưu tiên ứng viên có kinh nghiệm làm việc trong các dự án xây dựng và sửa nhà lớn.')
Insert into BaiDang Values ('3', N'Cần thợ điện nước sửa chữa cho căn hộ chung cư', N'Điện nước', N'Quận 2', N'Sửa chữa và bảo trì hệ thống điện và nước cho các căn hộ chung cư, đảm bảo an toàn và tiện nghi cho cư dân.', N'2024-3-4', N'1 - 2 năm', N'Kỹ năng sửa chữa và bảo trì hệ thống điện nước, hiểu biết về các tiêu chuẩn an toàn và vệ sinh liên quan.', N'Ưu tiên ứng viên có kinh nghiệm làm việc trong môi trường căn hộ chung cư và hiểu biết về hệ thống điện nước tại đây.')
Insert into BaiDang Values ('4', N'Tìm thợ bảo trì máy móc công nghiệp có kinh nghiệm', N'Bảo trì', N'Quận 3', N'Bảo trì, sửa chữa và duy trì các thiết bị và máy móc công nghiệp để đảm bảo hiệu suất hoạt động của nhà máy và xưởng sản xuất.', N'2024-3-4', N'1 - 2 năm', N'Kỹ năng sửa chữa máy móc công nghiệp, hiểu biết về các loại máy móc và thiết bị công nghiệp, có khả năng làm việc dưới áp lực và theo yêu cầu của sản xuất.', N'Ưu tiên ứng viên có kinh nghiệm làm việc trong môi trường sản xuất công nghiệp và hiểu biết về các quy trình bảo trì máy móc.')
Insert into BaiDang Values ('5', N'Gấp! Cần tuyển thợ sửa điện tại nhà', N'Điện nước', N'Quận 4', N'Thực hiện các công việc sửa chữa và nâng cấp nhà cửa, bao gồm sơn sửa, lắp đặt và cải thiện không gian sống.', N'2024-3-4', N'1 - 2 năm', N'Kỹ năng sửa chữa điện, hiểu biết về hệ thống điện và các tiêu chuẩn an toàn liên quan, có khả năng làm việc linh hoạt và hiệu quả.', N'Ưu tiên ứng viên có kinh nghiệm làm việc trong lĩnh vực sửa chữa điện và có khả năng tự chủ làm việc.')
Insert into BaiDang Values ('6', N'Tìm kiếm thợ điện tử sửa chữa máy tính xách tay', N'Điện tử', N'Quận 5', N'ửa chữa, nâng cấp và bảo trì các loại máy tính xách tay cho khách hàng cá nhân và doanh nghiệp.', N'2024-3-4', N'1 - 2 năm', N'Kỹ năng sửa chữa máy tính, hiểu biết về phần cứng và phần mềm máy tính, có khả năng làm việc dưới áp lực và theo yêu cầu của khách hàng.', N'Ưu tiên ứng viên có kinh nghiệm làm việc trong lĩnh vực sửa chữa máy tính xách tay và có khả năng giải quyết các vấn đề kỹ thuật phức tạp.')
Insert into BaiDang Values ('7', N'Cần thợ điện lạnh để kiểm tra và bảo dưỡng tủ lạnh', N'Điện lạnh', N'Quận 7', N'Kiểm tra, bảo dưỡng và sửa chữa các loại tủ lạnh để đảm bảo hoạt động hiệu quả và tiết kiệm năng lượng.', N'2024-3-4', N'1 - 2 năm', N'Kỹ năng sửa chữa và bảo dưỡng tủ lạnh, hiểu biết về nguyên lý hoạt động và cấu tạo của tủ lạnh, có khả năng làm việc tổ chức và chính xác.', N'Ưu tiên ứng viên có kinh nghiệm làm việc với các thương hiệu tủ lạnh phổ biến và hiểu biết về các vấn đề phổ biến mà người dùng gặp phải.')
Insert into BaiDang Values ('8', N'Tuyển dụng thợ gia sư dạy kèm môn Hóa học lớp 11', N'Gia sư', N'Điện lạnh', N'Cung cấp dịch vụ sửa chữa, bảo dưỡng và lắp đặt máy giặt tại nhà cho các hộ gia đình và khách hàng cá nhân.', N'2024-3-4', N'1 - 2 năm', N'Kỹ năng sửa chữa máy giặt, hiểu biết về cấu tạo và hoạt động của các loại máy giặt, có khả năng di chuyển linh hoạt và làm việc tại nhà khách hàng.', N'Ưu tiên ứng viên có kinh nghiệm làm việc trong lĩnh vực sửa chữa thiết bị gia đình.')
Insert into BaiDang Values ('9', N'Cần thợ sửa nhà để xây dựng phòng mới', N'Sửa nhà', N'Quận 8', N'Thực hiện xây dựng và sửa chữa phòng mới trong nhà, bao gồm việc làm móng, xây tường, lắp đặt cửa và cửa sổ, hoàn thiện nội thất và vật liệu xây dựng.', N'2024-3-4', N'1 - 2 năm', N'Kỹ năng làm việc chuyên nghiệp, hiểu biết về các kỹ thuật xây dựng và sửa nhà, có khả năng làm việc chăm chỉ, tỉ mỉ và sáng tạo trong việc thiết kế và hoàn thiện không gian sống.', N'Ưu tiên ứng viên có kinh nghiệm trong việc xây dựng và sửa chữa nhà cửa, đặc biệt là các dự án phức tạp và yêu cầu cao cấp.')
Insert into BaiDang Values ('10', N'Tìm kiếm thợ điện nước để lắp đặt hệ thống nước nóng', N'Điện nước', N'Quận 9', N'Lắp đặt và kết nối hệ thống nước nóng cho các gia đình, doanh nghiệp và công trình dân dụng, đảm bảo tính ổn định và an toàn của hệ thống, thực hiện các dự án lắp đặt mới hoặc nâng cấp hệ thống hiện có.', N'2024-3-4', N'1 - 2 năm', N'Kiến thức vững vàng về hệ thống nước nóng, kỹ năng lắp đặt và bảo trì, hiểu biết về các tiêu chuẩn an toàn và kỹ thuật trong ngành điện nước, có khả năng làm việc độc lập và theo đúng yêu cầu của dự án.', N'Ưu tiên ứng viên có bằng cấp và chứng chỉ liên quan, có kinh nghiệm trong lĩnh vực lắp đặt hệ thống nước nóng và làm việc trong các dự án lớn.')

